steps:
    # Build and deploy extract-service
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$_PROJECT_ID/extract-service', '.']
      dir: 'extract-service'
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$_PROJECT_ID/extract-service']
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
          - 'run'
          - 'deploy'
          - 'extract-service'
          - '--image=gcr.io/$_PROJECT_ID/extract-service'
          - '--region=asia-southeast1'
          - '--platform=managed'
          - '--allow-unauthenticated'
          - '--set-env-vars=GCS_BUCKET_NAME=etlpipelinehomeworkhbcloudrun-asia-southeast1'
      entrypoint: 'gcloud'

    # Build and deploy transform-service
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$_PROJECT_ID/transform-service', '.']
      dir: 'transform-service'
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$_PROJECT_ID/transform-service']
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
          - 'run'
          - 'deploy'
          - 'transform-service'
          - '--image=gcr.io/$_PROJECT_ID/transform-service'
          - '--region=asia-southeast1'
          - '--platform=managed'
          - '--allow-unauthenticated'
          - '--set-env-vars=GCS_BUCKET_NAME=etlpipelinehomeworkhbcloudrun-asia-southeast1,PROJECT_ID=training-triggering-pipeline'
      entrypoint: 'gcloud'

images:
    - 'gcr.io/$_PROJECT_ID/extract-service'
    - 'gcr.io/$_PROJECT_ID/transform-service'

substitutions:
    _PROJECT_ID: '' # Default value (can be overridden)
