steps:
    # Build and deploy the Extract service
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/extract-service', '.']
      dir: 'extract-service'
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/extract-service']
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
          - 'run'
          - 'deploy'
          - 'extract-service'
          - '--image=gcr.io/$PROJECT_ID/extract-service'
          - '--region=asia-southeast1'
          - '--platform=managed'
          - '--allow-unauthenticated'
      entrypoint: 'gcloud'

    # Build and deploy the Transform service
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/transform-service', '.']
      dir: 'transform-service'
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/transform-service']
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
          - 'run'
          - 'deploy'
          - 'transform-service'
          - '--image=gcr.io/$PROJECT_ID/transform-service'
          - '--region=asia-southeast1'
          - '--platform=managed'
          - '--allow-unauthenticated'
      entrypoint: 'gcloud'

images:
    - 'gcr.io/$PROJECT_ID/extract-service'
    - 'gcr.io/$PROJECT_ID/transform-service'
